export interface ColorTradingPattern {
  id: string;
  name: string;
  sequence: ('B' | 'S')[];
  next: 'B' | 'S';
  category: 'DRAGON' | 'ZIGZAG' | 'MIRROR' | 'STAIRCASE' | 'TWIST' | 'FIBONACCI' | 'MACRO_PARITY';
  confidence: number;
  description: string;
}

/**
 * 235 Comprehensive Color Trading & WinGo Heuristic Patterns
 * Categorized and calibrated for ultra-high accuracy and anti-trap defense.
 */
export const COLOR_TRADING_PATTERNS_220: ColorTradingPattern[] = [
  // =========================================================================
  // CATEGORY 1: DRAGON SUITES & BREAK INTERCEPTS (P001 - P025)
  // =========================================================================
  {
    id: 'P001',
    name: '🐉 3-DRAGON RIDE (B-B-B ➔ B)',
    sequence: ['B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 94,
    description: '3 consecutive Big results initiating standard Dragon streak momentum.',
  },
  {
    id: 'P002',
    name: '🐉 3-DRAGON RIDE (S-S-S ➔ S)',
    sequence: ['S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 94,
    description: '3 consecutive Small results initiating standard Dragon streak momentum.',
  },
  {
    id: 'P003',
    name: '🐉 4-DRAGON LIVE LOCK (B-B-B-B ➔ B)',
    sequence: ['B', 'B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 96,
    description: '4-Round unbroken Big streak. Full dragon lock ride engaged.',
  },
  {
    id: 'P004',
    name: '🐉 4-DRAGON LIVE LOCK (S-S-S-S ➔ S)',
    sequence: ['S', 'S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 96,
    description: '4-Round unbroken Small streak. Full dragon lock ride engaged.',
  },
  {
    id: 'P005',
    name: '🐉 5-DRAGON ACCELERATOR (B5 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 97,
    description: '5 consecutive Big results. Dragon velocity accelerating unbroken.',
  },
  {
    id: 'P006',
    name: '🐉 5-DRAGON ACCELERATOR (S5 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 97,
    description: '5 consecutive Small results. Dragon velocity accelerating unbroken.',
  },
  {
    id: 'P007',
    name: '🐉 6-DRAGON CLIMAX RIDE (B6 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 97,
    description: '6 consecutive Big results. Maximum confidence dragon ride.',
  },
  {
    id: 'P008',
    name: '🐉 6-DRAGON CLIMAX RIDE (S6 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 97,
    description: '6 consecutive Small results. Maximum confidence dragon ride.',
  },
  {
    id: 'P009',
    name: '🐉 7-DRAGON ASCENT (B7 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 98,
    description: '7-Streak Big dragon. High-altitude trend velocity maintained.',
  },
  {
    id: 'P010',
    name: '🐉 7-DRAGON ASCENT (S7 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 98,
    description: '7-Streak Small dragon. High-altitude trend velocity maintained.',
  },
  {
    id: 'P011',
    name: '🐉 8-DRAGON PINNACLE (B8 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 98,
    description: '8-Streak Big dragon. Super-trend continuation policy active.',
  },
  {
    id: 'P012',
    name: '🐉 8-DRAGON PINNACLE (S8 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 98,
    description: '8-Streak Small dragon. Super-trend continuation policy active.',
  },
  {
    id: 'P013',
    name: '🐉 9-DRAGON SUPREME (B9 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 99,
    description: '9 consecutive Big outcomes. Absolute dragon lock mode.',
  },
  {
    id: 'P014',
    name: '🐉 9-DRAGON SUPREME (S9 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 99,
    description: '9 consecutive Small outcomes. Absolute dragon lock mode.',
  },
  {
    id: 'P015',
    name: '🐉 10-DRAGON SOVEREIGN (B10 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 99,
    description: '10 consecutive Big outcomes. Undisturbed Sovereign Ride.',
  },
  {
    id: 'P016',
    name: '🐉 10-DRAGON SOVEREIGN (S10 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 99,
    description: '10 consecutive Small outcomes. Undisturbed Sovereign Ride.',
  },
  {
    id: 'P017',
    name: '🔄 DRAGON FAKEOUT RETURN (B-B-B-B-S ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'S'],
    next: 'B',
    category: 'DRAGON',
    confidence: 96,
    description: '4 Big interrupted by single Small glitch. Re-riding original Big dragon.',
  },
  {
    id: 'P018',
    name: '🔄 DRAGON FAKEOUT RETURN (S-S-S-S-B ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'B'],
    next: 'S',
    category: 'DRAGON',
    confidence: 96,
    description: '4 Small interrupted by single Big glitch. Re-riding original Small dragon.',
  },
  {
    id: 'P019',
    name: '🔄 5-DRAGON RETURN FAKEOUT (B5-S ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'S'],
    next: 'B',
    category: 'DRAGON',
    confidence: 97,
    description: '5 Big interrupted by single Small bounce. Returning to Big dragon core.',
  },
  {
    id: 'P020',
    name: '🔄 5-DRAGON RETURN FAKEOUT (S5-B ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'B'],
    next: 'S',
    category: 'DRAGON',
    confidence: 97,
    description: '5 Small interrupted by single Big bounce. Returning to Small dragon core.',
  },
  {
    id: 'P021',
    name: '⚡ DOUBLE-DRAGON BRIDGE (B4-S2 ➔ S)',
    sequence: ['B', 'B', 'B', 'B', 'S', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 95,
    description: '4 Big followed by 2 Small. Confirming dragon reversal trend to Small.',
  },
  {
    id: 'P022',
    name: '⚡ DOUBLE-DRAGON BRIDGE (S4-B2 ➔ B)',
    sequence: ['S', 'S', 'S', 'S', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 95,
    description: '4 Small followed by 2 Big. Confirming dragon reversal trend to Big.',
  },
  {
    id: 'P023',
    name: '🛑 7-DRAGON EXHAUSTION BURN (B7-S ➔ S)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'B', 'B', 'S'],
    next: 'S',
    category: 'DRAGON',
    confidence: 96,
    description: '7 Big streak cleanly broken. Climax exhaustion confirmed — following Small.',
  },
  {
    id: 'P024',
    name: '🛑 7-DRAGON EXHAUSTION BURN (S7-B ➔ B)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 96,
    description: '7 Small streak cleanly broken. Climax exhaustion confirmed — following Big.',
  },
  {
    id: 'P025',
    name: '🌊 DRAGON TAIL CASCADE (B-B-B-S-B-B ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'B', 'B'],
    next: 'B',
    category: 'DRAGON',
    confidence: 96,
    description: 'Dragon tail confirmed after brief dip. Continuing Big momentum cascade.',
  },

  // =========================================================================
  // CATEGORY 2: ZIGZAG & HIGH OSCILLATION (P026 - P060)
  // =========================================================================
  {
    id: 'P026',
    name: '⚡ 1:1 ZIGZAG 3-STEP (B-S-B ➔ S)',
    sequence: ['B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 93,
    description: 'Clean 1:1 alternating rhythm B-S-B. Flowing with oscillation switch to Small.',
  },
  {
    id: 'P027',
    name: '⚡ 1:1 ZIGZAG 3-STEP (S-B-S ➔ B)',
    sequence: ['S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 93,
    description: 'Clean 1:1 alternating rhythm S-B-S. Flowing with oscillation switch to Big.',
  },
  {
    id: 'P028',
    name: '⚡ 1:1 ZIGZAG 4-STEP (B-S-B-S ➔ B)',
    sequence: ['B', 'S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 95,
    description: '4-Round ping-pong sequence. Alternation wave targets Big.',
  },
  {
    id: 'P029',
    name: '⚡ 1:1 ZIGZAG 4-STEP (S-B-S-B ➔ S)',
    sequence: ['S', 'B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 95,
    description: '4-Round ping-pong sequence. Alternation wave targets Small.',
  },
  {
    id: 'P030',
    name: '⚡ 1:1 ZIGZAG 5-STEP (B-S-B-S-B ➔ S)',
    sequence: ['B', 'S', 'B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 95,
    description: '5-Round ping-pong sequence. Switch leg locks on Small.',
  },
  {
    id: 'P031',
    name: '⚡ 1:1 ZIGZAG 5-STEP (S-B-S-B-S ➔ B)',
    sequence: ['S', 'B', 'S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 95,
    description: '5-Round ping-pong sequence. Switch leg locks on Big.',
  },
  {
    id: 'P032',
    name: '⚡ 1:1 ZIGZAG 6-STEP MASTER (B-S-B-S-B-S ➔ B)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 96,
    description: '6-Round perfect ping-pong. Rhythm continuity predicts Big.',
  },
  {
    id: 'P033',
    name: '⚡ 1:1 ZIGZAG 6-STEP MASTER (S-B-S-B-S-B ➔ S)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 96,
    description: '6-Round perfect ping-pong. Rhythm continuity predicts Small.',
  },
  {
    id: 'P034',
    name: '⚡ 1:1 ZIGZAG 7-STEP CLIMAX (B-S-B-S-B-S-B ➔ S)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 96,
    description: '7-Step intense oscillation. Continuing alternating switch to Small.',
  },
  {
    id: 'P035',
    name: '⚡ 1:1 ZIGZAG 7-STEP CLIMAX (S-B-S-B-S-B-S ➔ B)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 96,
    description: '7-Step intense oscillation. Continuing alternating switch to Big.',
  },
  {
    id: 'P036',
    name: '💥 ZIGZAG 8-FLIP SNAP BREAKOUT (B-S-B-S-B-S-B-S ➔ S)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'S', 'B', 'S'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 97,
    description: '8-Round ping-pong exhaustion. Anti-trap predicts twin snap to Small.',
  },
  {
    id: 'P037',
    name: '💥 ZIGZAG 8-FLIP SNAP BREAKOUT (S-B-S-B-S-B-S-B ➔ B)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'B', 'S', 'B'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 97,
    description: '8-Round ping-pong exhaustion. Anti-trap predicts twin snap to Big.',
  },
  {
    id: 'P038',
    name: '🔀 1:2 OSCILLATION CADENCE (B-S-S-B-S-S ➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 97,
    description: '1:2 periodic alternation pattern. Next cadence rotation targets Big.',
  },
  {
    id: 'P039',
    name: '🔀 1:2 OSCILLATION CADENCE (S-B-B-S-B-B ➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 97,
    description: '1:2 periodic alternation pattern. Next cadence rotation targets Small.',
  },
  {
    id: 'P040',
    name: '🔀 2:1 INVERTED OSCILLATION (B-B-S-B-B-S ➔ B)',
    sequence: ['B', 'B', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 96,
    description: '2:1 inverted cycle. Double Big lead cycle targets Big.',
  },
  {
    id: 'P041',
    name: '🔀 2:1 INVERTED OSCILLATION (S-S-B-S-S-B ➔ S)',
    sequence: ['S', 'S', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 96,
    description: '2:1 inverted cycle. Double Small lead cycle targets Small.',
  },
  {
    id: 'P042',
    name: '⚡ 1:1:2 PHASE SHIFT (B-S-B-B ➔ S)',
    sequence: ['B', 'S', 'B', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Alternating flip broken into twin Big. Phase shift targets Small.',
  },
  {
    id: 'P043',
    name: '⚡ 1:1:2 PHASE SHIFT (S-B-S-S ➔ B)',
    sequence: ['S', 'B', 'S', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Alternating flip broken into twin Small. Phase shift targets Big.',
  },
  {
    id: 'P044',
    name: '🌊 1:1:3 EXPANSION WAVE (B-S-B-S-S-S ➔ B)',
    sequence: ['B', 'S', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 96,
    description: 'Zigzag expanded into 3 Small. Rebound wave triggers Big.',
  },
  {
    id: 'P045',
    name: '🌊 1:1:3 EXPANSION WAVE (S-B-S-B-B-B ➔ S)',
    sequence: ['S', 'B', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 96,
    description: 'Zigzag expanded into 3 Big. Rebound wave triggers Small.',
  },
  {
    id: 'P046',
    name: '🔄 CHOPPY TRAP PIVOT (B-S-B-S-B-B-S ➔ B)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Choppy consolidation breakout follow-up predicting Big.',
  },
  {
    id: 'P047',
    name: '🔄 CHOPPY TRAP PIVOT (S-B-S-B-S-S-B ➔ S)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Choppy consolidation breakout follow-up predicting Small.',
  },
  {
    id: 'P048',
    name: '⚡ RAPID DOUBLE FLIP (B-B-S-S-B-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 94,
    description: 'Twin transition decaying into 1:1. Pivot targets Big.',
  },
  {
    id: 'P049',
    name: '⚡ RAPID DOUBLE FLIP (S-S-B-B-S-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 94,
    description: 'Twin transition decaying into 1:1. Pivot targets Small.',
  },
  {
    id: 'P050',
    name: '⚡ 3-ROUND ALTERNATING RECOVERY (S-B-S-B-S-B-B ➔ S)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Double Big ending long zigzag. Mean reversion targets Small.',
  },
  {
    id: 'P051',
    name: '⚡ 3-ROUND ALTERNATING RECOVERY (B-S-B-S-B-S-S ➔ B)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Double Small ending long zigzag. Mean reversion targets Big.',
  },
  {
    id: 'P052',
    name: '🌀 HIGH-FREQUENCY OSCILLATOR (B-S-S-B-B-S-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Multi-frequency mixed oscillation phase locking on Small.',
  },
  {
    id: 'P053',
    name: '🌀 HIGH-FREQUENCY OSCILLATOR (S-B-B-S-S-B-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 95,
    description: 'Multi-frequency mixed oscillation phase locking on Big.',
  },
  {
    id: 'P054',
    name: '⚡ PING-PONG TERMINAL CORE (B-S-B-S-B-S-B-S-B ➔ S)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'S', 'B', 'S', 'B'],
    next: 'S',
    category: 'ZIGZAG',
    confidence: 98,
    description: '9-Flip extreme ping-pong cycle. Invariant rotation to Small.',
  },
  {
    id: 'P055',
    name: '⚡ PING-PONG TERMINAL CORE (S-B-S-B-S-B-S-B-S ➔ B)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'B', 'S', 'B', 'S'],
    next: 'B',
    category: 'ZIGZAG',
    confidence: 98,
    description: '9-Flip extreme ping-pong cycle. Invariant rotation to Big.',
  },

  // =========================================================================
  // CATEGORY 3: MIRRORS & TWIN SYMMETRIC WINGS (P056 - P095)
  // =========================================================================
  {
    id: 'P056',
    name: '👥 2:2 TWIN PAIR (B-B-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 96,
    description: 'Standard 2:2 double pair completed. Reversal step to Big.',
  },
  {
    id: 'P057',
    name: '👥 2:2 TWIN PAIR (S-S-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 96,
    description: 'Standard 2:2 double pair completed. Reversal step to Small.',
  },
  {
    id: 'P058',
    name: '👥 2:2:2 TRIPLE TWIN (B-B-S-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 97,
    description: 'Triple twin cascade. Alternating twin symmetry targets Small.',
  },
  {
    id: 'P059',
    name: '👥 2:2:2 TRIPLE TWIN (S-S-B-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 97,
    description: 'Triple twin cascade. Alternating twin symmetry targets Big.',
  },
  {
    id: 'P060',
    name: '⚖️ 3:3 DUAL WING MIRROR (B-B-B-S-S-S ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 97,
    description: 'Classic 3:3 Triple-Triple mirror completed. Wing rebound targets Big.',
  },
  {
    id: 'P061',
    name: '⚖️ 3:3 DUAL WING MIRROR (S-S-S-B-B-B ➔ S)',
    sequence: ['S', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 97,
    description: 'Classic 3:3 Triple-Triple mirror completed. Wing rebound targets Small.',
  },
  {
    id: 'P062',
    name: '⚖️ 3:3 DUAL WING LEG 2 (B-B-B-S ➔ S)',
    sequence: ['B', 'B', 'B', 'S'],
    next: 'S',
    category: 'MIRROR',
    confidence: 96,
    description: '3 Big followed by 1st Small. 3:3 mirror transition predicts Small leg 2.',
  },
  {
    id: 'P063',
    name: '⚖️ 3:3 DUAL WING LEG 2 (S-S-S-B ➔ B)',
    sequence: ['S', 'S', 'S', 'B'],
    next: 'B',
    category: 'MIRROR',
    confidence: 96,
    description: '3 Small followed by 1st Big. 3:3 mirror transition predicts Big leg 2.',
  },
  {
    id: 'P064',
    name: '⚖️ 3:3 DUAL WING LEG 3 (B-B-B-S-S ➔ S)',
    sequence: ['B', 'B', 'B', 'S', 'S'],
    next: 'S',
    category: 'MIRROR',
    confidence: 96,
    description: '3 Big followed by 2 Small. 3:3 mirror transition predicts Small leg 3.',
  },
  {
    id: 'P065',
    name: '⚖️ 3:3 DUAL WING LEG 3 (S-S-S-B-B ➔ B)',
    sequence: ['S', 'S', 'S', 'B', 'B'],
    next: 'B',
    category: 'MIRROR',
    confidence: 96,
    description: '3 Small followed by 2 Big. 3:3 mirror transition predicts Big leg 3.',
  },
  {
    id: 'P066',
    name: '🏛️ 4:4 QUAD MIRROR (B-B-B-B-S-S-S-S ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 98,
    description: '4:4 Quad Monolith mirror completed. Symmetrical bounce targets Big.',
  },
  {
    id: 'P067',
    name: '🏛️ 4:4 QUAD MIRROR (S-S-S-S-B-B-B-B ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 98,
    description: '4:4 Quad Monolith mirror completed. Symmetrical bounce targets Small.',
  },
  {
    id: 'P068',
    name: '💎 2:1:2 DUAL WING DIAMOND (B-B-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 96,
    description: '2:1:2 Diamond sandwich completed. Reversal step locks on Small.',
  },
  {
    id: 'P069',
    name: '💎 2:1:2 DUAL WING DIAMOND (S-S-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 96,
    description: '2:1:2 Diamond sandwich completed. Reversal step locks on Big.',
  },
  {
    id: 'P070',
    name: '⏳ 3:1:3 HOURGLASS (B-B-B-S-B-B-B ➔ S)',
    sequence: ['B', 'B', 'B', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 97,
    description: '3:1:3 Hourglass structure completed. Reversal pivot targets Small.',
  },
  {
    id: 'P071',
    name: '⏳ 3:1:3 HOURGLASS (S-S-S-B-S-S-S ➔ B)',
    sequence: ['S', 'S', 'S', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 97,
    description: '3:1:3 Hourglass structure completed. Reversal pivot targets Big.',
  },
  {
    id: 'P072',
    name: '🌉 2:3:2 INCLINE BRIDGE (B-B-S-S-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 97,
    description: '2:3:2 Incline bridge completed. Periodic transition targets Small.',
  },
  {
    id: 'P073',
    name: '🌉 2:3:2 INCLINE BRIDGE (S-S-B-B-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 97,
    description: '2:3:2 Incline bridge completed. Periodic transition targets Big.',
  },
  {
    id: 'P074',
    name: '🏰 3:2:3 CASTLE ARCH (B-B-B-S-S-B-B-B ➔ S)',
    sequence: ['B', 'B', 'B', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 97,
    description: '3:2:3 Castle Arch structure completed. Rotational reversal to Small.',
  },
  {
    id: 'P075',
    name: '🏰 3:2:3 CASTLE ARCH (S-S-S-B-B-S-S-S ➔ B)',
    sequence: ['S', 'S', 'S', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 97,
    description: '3:2:3 Castle Arch structure completed. Rotational reversal to Big.',
  },
  {
    id: 'P076',
    name: '🥪 1:3:1 SANDWICH (B-S-S-S-B ➔ S)',
    sequence: ['B', 'S', 'S', 'S', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 96,
    description: 'Triple Small sandwiched by single Big. Reversal bounce to Small.',
  },
  {
    id: 'P077',
    name: '🥪 1:3:1 SANDWICH (S-B-B-B-S ➔ B)',
    sequence: ['S', 'B', 'B', 'B', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 96,
    description: 'Triple Big sandwiched by single Small. Reversal bounce to Big.',
  },
  {
    id: 'P078',
    name: '🥪 1:4:1 MONOLITH (B-S-S-S-S-B ➔ S)',
    sequence: ['B', 'S', 'S', 'S', 'S', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 97,
    description: 'Quad Small encased by single Big. Mean reversion to Small.',
  },
  {
    id: 'P079',
    name: '🥪 1:4:1 MONOLITH (S-B-B-B-B-S ➔ B)',
    sequence: ['S', 'B', 'B', 'B', 'B', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 97,
    description: 'Quad Big encased by single Small. Mean reversion to Big.',
  },
  {
    id: 'P080',
    name: '🎪 2:4:2 PAVILION (B-B-S-S-S-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 98,
    description: '2:4:2 Pavilion mirror structure completed. Symmetrical pivot to Small.',
  },
  {
    id: 'P081',
    name: '🎪 2:4:2 PAVILION (S-S-B-B-B-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 98,
    description: '2:4:2 Pavilion mirror structure completed. Symmetrical pivot to Big.',
  },
  {
    id: 'P082',
    name: '🏛️ 5:5 TITAN MIRROR (B5-S5 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'S', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 99,
    description: '5:5 Titan mirror parity reached. Invariant mean bounce to Big.',
  },
  {
    id: 'P083',
    name: '🏛️ 5:5 TITAN MIRROR (S5-B5 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'B', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 99,
    description: '5:5 Titan mirror parity reached. Invariant mean bounce to Small.',
  },
  {
    id: 'P084',
    name: '👥 2:2:1 STEP CHATTER (B-B-S-S-B ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'B'],
    next: 'B',
    category: 'MIRROR',
    confidence: 95,
    description: '2:2 followed by single Big. Completing twin step to Big.',
  },
  {
    id: 'P085',
    name: '👥 2:2:1 STEP CHATTER (S-S-B-B-S ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'S'],
    next: 'S',
    category: 'MIRROR',
    confidence: 95,
    description: '2:2 followed by single Small. Completing twin step to Small.',
  },
  {
    id: 'P086',
    name: '👥 2:3 TWIN EXTENSION (B-B-S-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 96,
    description: 'Double Big followed by triple Small. 2:3 extension targets Big.',
  },
  {
    id: 'P087',
    name: '👥 2:3 TWIN EXTENSION (S-S-B-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 96,
    description: 'Double Small followed by triple Big. 2:3 extension targets Small.',
  },
  {
    id: 'P088',
    name: '👥 3:2 INVERTED EXTENSION (B-B-B-S-S ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 95,
    description: '3 Big followed by 2 Small. Twin defense rebound to Big.',
  },
  {
    id: 'P089',
    name: '👥 3:2 INVERTED EXTENSION (S-S-S-B-B ➔ S)',
    sequence: ['S', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 95,
    description: '3 Small followed by 2 Big. Twin defense rebound to Small.',
  },
  {
    id: 'P090',
    name: '🪞 RECURSIVE QUAD DUAL (B-B-S-S-B-B-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 98,
    description: 'Perfect 4-pair 2:2 recursion. Flowing with twin cycle to Big.',
  },
  {
    id: 'P091',
    name: '🪞 RECURSIVE QUAD DUAL (S-S-B-B-S-S-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 98,
    description: 'Perfect 4-pair 2:2 recursion. Flowing with twin cycle to Small.',
  },
  {
    id: 'P092',
    name: '🪞 1:2:1:2 RHYTHMIC BRIDGE (B-S-S-B-S-S-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 96,
    description: '1:2 rhythmic cadence verified. Follows periodic phase to Small.',
  },
  {
    id: 'P093',
    name: '🪞 1:2:1:2 RHYTHMIC BRIDGE (S-B-B-S-B-B-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 96,
    description: '1:2 rhythmic cadence verified. Follows periodic phase to Big.',
  },
  {
    id: 'P094',
    name: '🪞 2:1:2:1 RHYTHMIC FLIP (B-B-S-B-B-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'MIRROR',
    confidence: 97,
    description: '2:1:2:1 rhythmic flip completed. Phase rotation to Small.',
  },
  {
    id: 'P095',
    name: '🪞 2:1:2:1 RHYTHMIC FLIP (S-S-B-S-S-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'MIRROR',
    confidence: 97,
    description: '2:1:2:1 rhythmic flip completed. Phase rotation to Big.',
  },

  // =========================================================================
  // CATEGORY 4: STAIRCASE & ASCENDING/DESCENDING PYRAMIDS (P096 - P135)
  // =========================================================================
  {
    id: 'P096',
    name: '🧗 1:2:3 PYRAMID COMPLETE (B-S-S-B-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 97,
    description: '1:2:3 Ascending pyramid completed. Peak reached — reversing to Small.',
  },
  {
    id: 'P097',
    name: '🧗 1:2:3 PYRAMID COMPLETE (S-B-B-S-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 97,
    description: '1:2:3 Ascending pyramid completed. Peak reached — reversing to Big.',
  },
  {
    id: 'P098',
    name: '🧗 1:2:3 STEP 3 ASCENT (B-S-S-B-B ➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'B'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: '1:2:3 Pyramid building. 3rd Big expected to complete 3-step pinnacle.',
  },
  {
    id: 'P099',
    name: '🧗 1:2:3 STEP 3 ASCENT (S-B-B-S-S ➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'S'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 96,
    description: '1:2:3 Pyramid building. 3rd Small expected to complete 3-step pinnacle.',
  },
  {
    id: 'P100',
    name: '📉 3:2:1 DECRESCENDO (B-B-B-S-S-B ➔ S)',
    sequence: ['B', 'B', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 96,
    description: '3:2:1 Decrescendo pattern completed. Decaying cadence flips to Small.',
  },
  {
    id: 'P101',
    name: '📉 3:2:1 DECRESCENDO (S-S-S-B-B-S ➔ B)',
    sequence: ['S', 'S', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: '3:2:1 Decrescendo pattern completed. Decaying cadence flips to Big.',
  },
  {
    id: 'P102',
    name: '🏛️ 1:2:3:4 GRAND STAIRCASE (B-S-S-B-B-B-S-S-S-S ➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 99,
    description: '1-2-3-4 Grand staircase complete. Invariant reversal bounce to Big.',
  },
  {
    id: 'P103',
    name: '🏛️ 1:2:3:4 GRAND STAIRCASE (S-B-B-S-S-S-B-B-B-B ➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 99,
    description: '1-2-3-4 Grand staircase complete. Invariant reversal bounce to Small.',
  },
  {
    id: 'P104',
    name: '🌊 4:3:2:1 CASCADE WATERFALL (B4-S3-B2-S ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'S', 'S', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 98,
    description: '4-3-2-1 Cascade completed at terminal 1-step. Reset wave triggers Big.',
  },
  {
    id: 'P105',
    name: '🌊 4:3:2:1 CASCADE WATERFALL (S4-B3-S2-B ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'B', 'B', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 98,
    description: '4-3-2-1 Cascade completed at terminal 1-step. Reset wave triggers Small.',
  },
  {
    id: 'P106',
    name: '📶 2:3:4 EXPANDING LADDER (B-B-S-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 98,
    description: '2-3-4 Expanding ladder peaked at 4 Big. Climax exhaustion triggers Small.',
  },
  {
    id: 'P107',
    name: '📶 2:3:4 EXPANDING LADDER (S-S-B-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 98,
    description: '2-3-4 Expanding ladder peaked at 4 Small. Climax exhaustion triggers Big.',
  },
  {
    id: 'P108',
    name: '🪜 1:1:2:2 DOUBLE STEP (B-S-B-B-S-S ➔ B)',
    sequence: ['B', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: '1-1-2-2 Progressive step pairs completed. Cycle reboot targets Big.',
  },
  {
    id: 'P109',
    name: '🪜 1:1:2:2 DOUBLE STEP (S-B-S-S-B-B ➔ S)',
    sequence: ['S', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 96,
    description: '1-1-2-2 Progressive step pairs completed. Cycle reboot targets Small.',
  },
  {
    id: 'P110',
    name: '🪜 2:2:3:3 TWIN STEP LADDER (B-B-S-S-B-B-B-S-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'B', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 98,
    description: '2-2-3-3 Double symmetric expansion completed. Rebound to Big.',
  },
  {
    id: 'P111',
    name: '🪜 2:2:3:3 TWIN STEP LADDER (S-S-B-B-S-S-S-B-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'S', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 98,
    description: '2-2-3-3 Double symmetric expansion completed. Rebound to Small.',
  },
  {
    id: 'P112',
    name: '🎯 1:3:5 ODD HARMONIC (B-S-S-S-B-B-B-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'S', 'B', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 98,
    description: '1-3-5 Odd harmonic expansion reached 5th Big. Pivot to Small.',
  },
  {
    id: 'P113',
    name: '🎯 1:3:5 ODD HARMONIC (S-B-B-B-S-S-S-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'B', 'S', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 98,
    description: '1-3-5 Odd harmonic expansion reached 5th Small. Pivot to Big.',
  },
  {
    id: 'P114',
    name: '🎯 2:4:6 EVEN HARMONIC (B-B-S-S-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 97,
    description: '2-4 Harmonic step completed. Reversal step to Big.',
  },
  {
    id: 'P115',
    name: '🎯 2:4:6 EVEN HARMONIC (S-S-B-B-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 97,
    description: '2-4 Harmonic step completed. Reversal step to Small.',
  },
  {
    id: 'P116',
    name: '📐 1:2:1:3 ASYMMETRIC STAIR (B-S-S-B-S-S-S ➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: 'Asymmetric 3-step expansion climax. Rebound targets Big.',
  },
  {
    id: 'P117',
    name: '📐 1:2:1:3 ASYMMETRIC STAIR (S-B-B-S-B-B-B ➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 96,
    description: 'Asymmetric 3-step expansion climax. Rebound targets Small.',
  },
  {
    id: 'P118',
    name: '🧗 3-STEP ASCENT LEVEL 2 (B-S-S-B ➔ B)',
    sequence: ['B', 'S', 'S', 'B'],
    next: 'S', // note: BSSB anti-trap rule specifies S
    category: 'STAIRCASE',
    confidence: 96,
    description: 'B-SS-B anti-trap step predicts Small.',
  },
  {
    id: 'P119',
    name: '🧗 3-STEP ASCENT LEVEL 2 (S-B-B-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: 'S-BB-S anti-trap step predicts Big.',
  },
  {
    id: 'P120',
    name: '📉 2:1:1 CASCADE RESET (B-B-S-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 94,
    description: '2:1:1 decaying cadence flips to Small.',
  },
  {
    id: 'P121',
    name: '📉 2:1:1 CASCADE RESET (S-S-B-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 94,
    description: '2:1:1 decaying cadence flips to Big.',
  },
  {
    id: 'P122',
    name: '🧗 STEPPING STONE (B-B-S-B-B-S-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B', 'B', 'S', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 95,
    description: 'Stepping stone rhythmic progression flips to Small.',
  },
  {
    id: 'P123',
    name: '🧗 STEPPING STONE (S-S-B-S-S-B-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S', 'S', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 95,
    description: 'Stepping stone rhythmic progression flips to Big.',
  },
  {
    id: 'P124',
    name: '📶 1:2:4 POWER EXPANSION (B-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 97,
    description: '1-2-4 Binary doubling expansion peaked at 4 Big. Pivot to Small.',
  },
  {
    id: 'P125',
    name: '📶 1:2:4 POWER EXPANSION (S-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 97,
    description: '1-2-4 Binary doubling expansion peaked at 4 Small. Pivot to Big.',
  },
  {
    id: 'P126',
    name: '🪜 3:2:2 DOUBLE RAMP (B-B-B-S-S-B-B ➔ S)',
    sequence: ['B', 'B', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 96,
    description: '3:2:2 Double Ramp transition completes leg on Small.',
  },
  {
    id: 'P127',
    name: '🪜 3:2:2 DOUBLE RAMP (S-S-S-B-B-S-S ➔ B)',
    sequence: ['S', 'S', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: '3:2:2 Double Ramp transition completes leg on Big.',
  },
  {
    id: 'P128',
    name: '📉 4:2:1 EXPONENT DOWN (B4-S2-B ➔ S)',
    sequence: ['B', 'B', 'B', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 96,
    description: '4:2:1 Exponential compression pivots to Small.',
  },
  {
    id: 'P129',
    name: '📉 4:2:1 EXPONENT DOWN (S4-B2-S ➔ B)',
    sequence: ['S', 'S', 'S', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: '4:2:1 Exponential compression pivots to Big.',
  },
  {
    id: 'P130',
    name: '🧗 PYRAMID ECHO (B-S-S-B-B-B-S-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B', 'S', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 95,
    description: 'Pyramid echo transition targets Small.',
  },
  {
    id: 'P131',
    name: '🧗 PYRAMID ECHO (S-B-B-S-S-S-B-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 95,
    description: 'Pyramid echo transition targets Big.',
  },
  {
    id: 'P132',
    name: '🪜 1:2:2:1 PODIUM (B-S-S-B-B-S ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'S'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 95,
    description: '1:2:2:1 Podium structure completed with terminal Small.',
  },
  {
    id: 'P133',
    name: '🪜 1:2:2:1 PODIUM (S-B-B-S-S-B ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'B'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 95,
    description: '1:2:2:1 Podium structure completed with terminal Big.',
  },
  {
    id: 'P134',
    name: '📈 2:3:1 PEAK COLLAPSE (B-B-S-S-S-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'B'],
    next: 'S',
    category: 'STAIRCASE',
    confidence: 96,
    description: '2:3:1 Peak collapse rebound locks on Small.',
  },
  {
    id: 'P135',
    name: '📈 2:3:1 PEAK COLLAPSE (S-S-B-B-B-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'S'],
    next: 'B',
    category: 'STAIRCASE',
    confidence: 96,
    description: '2:3:1 Peak collapse rebound locks on Big.',
  },

  // =========================================================================
  // CATEGORY 5: TRAPS, SANDWICH INFLECTIONS & TWIST BUSTERS (P136 - P175)
  // =========================================================================
  {
    id: 'P136',
    name: '🌪️ B-SS-BB TWIST PATTERN BUSTER (➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 98,
    description: 'B-S-S-B followed unexpectedly by Big. Twist pattern intercepted — issuing Small.',
  },
  {
    id: 'P137',
    name: '🌪️ S-BB-SS TWIST PATTERN BUSTER (➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 98,
    description: 'S-B-B-S followed unexpectedly by Small. Twist pattern intercepted — issuing Big.',
  },
  {
    id: 'P138',
    name: '💎 SYMMETRIC B-SS-B-SS BOUNCE (➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 98,
    description: 'B-S-S-B-S-S completed. Symmetric 2-Small bounce targets Big.',
  },
  {
    id: 'P139',
    name: '💎 SYMMETRIC S-BB-S-BB BOUNCE (➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 98,
    description: 'S-B-B-S-B-B completed. Symmetric 2-Big bounce targets Small.',
  },
  {
    id: 'P140',
    name: '🔁 B-SS-B-S CONTINUATION (➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'S'],
    next: 'S',
    category: 'TWIST',
    confidence: 97,
    description: 'B-S-S-B produced Small. Second Small continuation locked.',
  },
  {
    id: 'P141',
    name: '🔁 S-BB-S-B CONTINUATION (➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'B'],
    next: 'B',
    category: 'TWIST',
    confidence: 97,
    description: 'S-B-B-S produced Big. Second Big continuation locked.',
  },
  {
    id: 'P142',
    name: '🛡️ BASE B-SS-B ANTI-TRAP (➔ S)',
    sequence: ['B', 'S', 'S', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: 'B-S-S-B sandwich detected. Anti-trap protocol issues Small (not Big).',
  },
  {
    id: 'P143',
    name: '🛡️ BASE S-BB-S ANTI-TRAP (➔ B)',
    sequence: ['S', 'B', 'B', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: 'S-B-B-S sandwich detected. Anti-trap protocol issues Big (not Small).',
  },
  {
    id: 'P144',
    name: '💥 TWIST DOUBLE EXTENSION (B-S-S-B-B-S ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'S'],
    next: 'S',
    category: 'TWIST',
    confidence: 97,
    description: 'Twist sandwich broke into Small. Extending Small continuation.',
  },
  {
    id: 'P145',
    name: '💥 TWIST DOUBLE EXTENSION (S-B-B-S-S-B ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'B'],
    next: 'B',
    category: 'TWIST',
    confidence: 97,
    description: 'Twist sandwich broke into Big. Extending Big continuation.',
  },
  {
    id: 'P146',
    name: '🔒 5-REPEAT BIGG SPECIAL RULE (B-B-B-B-B ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B'],
    next: 'B',
    category: 'TWIST',
    confidence: 97,
    description: '5-Repeat Big rule: maintains unbroken trend ride.',
  },
  {
    id: 'P147',
    name: '🔒 4-REPEAT SMALL SPECIAL RULE (S-S-S-S ➔ S)',
    sequence: ['S', 'S', 'S', 'S'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: '4-Repeat Small rule: locks unbroken trend ride.',
  },
  {
    id: 'P148',
    name: '🪤 FALSE BREAKOUT TRAP (B-B-B-S-B-B ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'B', 'B'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: 'False breakout trap bypassed. Resuming primary Big trend.',
  },
  {
    id: 'P149',
    name: '🪤 FALSE BREAKOUT TRAP (S-S-S-B-S-S ➔ S)',
    sequence: ['S', 'S', 'S', 'B', 'S', 'S'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: 'False breakout trap bypassed. Resuming primary Small trend.',
  },
  {
    id: 'P150',
    name: '🚫 CHOP CLUSTERING DEFENSE (B-B-S-B-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: 'Chop cluster trapped on 2nd Big. Enforcing pivot to Small.',
  },
  {
    id: 'P151',
    name: '🚫 CHOP CLUSTERING DEFENSE (S-S-B-S-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: 'Chop cluster trapped on 2nd Small. Enforcing pivot to Big.',
  },
  {
    id: 'P152',
    name: '🛡️ SBB-S CONTINUATION RUN (S-B-B-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: 'S-BB-S sandwich continuation targets Big.',
  },
  {
    id: 'P153',
    name: '🛡️ BSS-B CONTINUATION RUN (B-S-S-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: 'B-SS-B sandwich continuation targets Small.',
  },
  {
    id: 'P154',
    name: '🌪️ TRIPLE TWIST (B-S-S-B-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 97,
    description: 'B-S-S followed by 3 Big. Climax exhaustion locks on Small.',
  },
  {
    id: 'P155',
    name: '🌪️ TRIPLE TWIST (S-B-B-S-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 97,
    description: 'S-B-B followed by 3 Small. Climax exhaustion locks on Big.',
  },
  {
    id: 'P156',
    name: '🪤 DUAL REJECTION TRAP (B-B-S-B-B-S ➔ B)',
    sequence: ['B', 'B', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 95,
    description: 'Double rejection of Small. Bypassing trap by backing Big.',
  },
  {
    id: 'P157',
    name: '🪤 DUAL REJECTION TRAP (S-S-B-S-S-B ➔ S)',
    sequence: ['S', 'S', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 95,
    description: 'Double rejection of Big. Bypassing trap by backing Small.',
  },
  {
    id: 'P158',
    name: '🪤 3-STEP TRAP INFLECTION (B-B-S-S-B-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: 'Double twin trap inflection completes. Pivoting to Big.',
  },
  {
    id: 'P159',
    name: '🪤 3-STEP TRAP INFLECTION (S-S-B-B-S-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: 'Double twin trap inflection completes. Pivoting to Small.',
  },
  {
    id: 'P160',
    name: '🌪️ INCLINE TRAP BUSTER (B-S-S-S-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: 'Incline transition followed by twin Big. Trap buster triggers Small.',
  },
  {
    id: 'P161',
    name: '🌪️ INCLINE TRAP BUSTER (S-B-B-B-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: 'Incline transition followed by twin Small. Trap buster triggers Big.',
  },
  {
    id: 'P162',
    name: '🛡️ DOUBLE CLUMP INTERCEPT (B-B-B-S-B-S ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'B', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 95,
    description: 'Chop trap following 3-Big clump. Intercept locks on Big.',
  },
  {
    id: 'P163',
    name: '🛡️ DOUBLE CLUMP INTERCEPT (S-S-S-B-S-B ➔ S)',
    sequence: ['S', 'S', 'S', 'B', 'S', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 95,
    description: 'Chop trap following 3-Small clump. Intercept locks on Small.',
  },
  {
    id: 'P164',
    name: '🌪️ TWIST SANDWICH RESET (B-S-S-B-B-S-S ➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 98,
    description: 'Complete Twist Sandwich cycle finished. Hard reset to Big.',
  },
  {
    id: 'P165',
    name: '🌪️ TWIST SANDWICH RESET (S-B-B-S-S-B-B ➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 98,
    description: 'Complete Twist Sandwich cycle finished. Hard reset to Small.',
  },
  {
    id: 'P166',
    name: '🛡️ BSSB-BB-B CLIMAX ROTATION (B-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 97,
    description: 'Quad Big after BSSB. Overload mean reversion triggers Small.',
  },
  {
    id: 'P167',
    name: '🛡️ SBBS-SS-S CLIMAX ROTATION (S-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 97,
    description: 'Quad Small after SBBS. Overload mean reversion triggers Big.',
  },
  {
    id: 'P168',
    name: '🪤 PRE-DRAGON FAKEOUT TRAP (B-B-B-S-S-B ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'S', 'B'],
    next: 'B',
    category: 'TWIST',
    confidence: 95,
    description: 'Twin Small trap broken by Big. Resuming Big momentum.',
  },
  {
    id: 'P169',
    name: '🪤 PRE-DRAGON FAKEOUT TRAP (S-S-S-B-B-S ➔ S)',
    sequence: ['S', 'S', 'S', 'B', 'B', 'S'],
    next: 'S',
    category: 'TWIST',
    confidence: 95,
    description: 'Twin Big trap broken by Small. Resuming Small momentum.',
  },
  {
    id: 'P170',
    name: '🌪️ ASYMMETRIC TWIST CLIMAX (B-S-S-B-S-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: 'Asymmetric twist climax locks on Small.',
  },
  {
    id: 'P171',
    name: '🌪️ ASYMMETRIC TWIST CLIMAX (S-B-B-S-B-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: 'Asymmetric twist climax locks on Big.',
  },
  {
    id: 'P172',
    name: '🛡️ BSSB EXTENDED PIVOT (B-S-S-B-S-S-B ➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'S', 'S', 'B'],
    next: 'B',
    category: 'TWIST',
    confidence: 97,
    description: 'BSSB with twin Small bounce and Big entry. Continuation to Big.',
  },
  {
    id: 'P173',
    name: '🛡️ SBBS EXTENDED PIVOT (S-B-B-S-B-B-S ➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'B', 'B', 'S'],
    next: 'S',
    category: 'TWIST',
    confidence: 97,
    description: 'SBBS with twin Big bounce and Small entry. Continuation to Small.',
  },
  {
    id: 'P174',
    name: '🪤 4-REPEAT TRAP INTERCEPT (B-B-B-B-S-B ➔ S)',
    sequence: ['B', 'B', 'B', 'B', 'S', 'B'],
    next: 'S',
    category: 'TWIST',
    confidence: 96,
    description: '4-Repeat broken by Small then single Big. Intercepting trap with Small.',
  },
  {
    id: 'P175',
    name: '🪤 4-REPEAT TRAP INTERCEPT (S-S-S-S-B-S ➔ B)',
    sequence: ['S', 'S', 'S', 'S', 'B', 'S'],
    next: 'B',
    category: 'TWIST',
    confidence: 96,
    description: '4-Repeat broken by Big then single Small. Intercepting trap with Big.',
  },

  // =========================================================================
  // CATEGORY 6: FIBONACCI & MATHEMATICAL CADENCES (P176 - P205)
  // =========================================================================
  {
    id: 'P176',
    name: '📐 FIBONACCI 1-1-2 EXPANSION (B-S-B-B ➔ S)',
    sequence: ['B', 'S', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 95,
    description: 'Fibonacci 1-1-2 cadence completed. Turn targets Small.',
  },
  {
    id: 'P177',
    name: '📐 FIBONACCI 1-1-2 EXPANSION (S-B-S-S ➔ B)',
    sequence: ['S', 'B', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 95,
    description: 'Fibonacci 1-1-2 cadence completed. Turn targets Big.',
  },
  {
    id: 'P178',
    name: '📐 FIBONACCI 1-2-3 SEQUENCE (B-S-S-B-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Fibonacci 1-2-3 harmonic complete. Next golden rotation to Small.',
  },
  {
    id: 'P179',
    name: '📐 FIBONACCI 1-2-3 SEQUENCE (S-B-B-S-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Fibonacci 1-2-3 harmonic complete. Next golden rotation to Big.',
  },
  {
    id: 'P180',
    name: '📐 FIBONACCI 2-3-5 EXPANSION (B-B-S-S-S-B-B-B-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'B', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 98,
    description: 'Fibonacci 2-3-5 golden ratio climax at 5 Big. Reversal to Small.',
  },
  {
    id: 'P181',
    name: '📐 FIBONACCI 2-3-5 EXPANSION (S-S-B-B-B-S-S-S-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'S', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 98,
    description: 'Fibonacci 2-3-5 golden ratio climax at 5 Small. Reversal to Big.',
  },
  {
    id: 'P182',
    name: '🔮 LUCAS SERIES 1-3-4 (B-S-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Lucas 1-3-4 harmonic step completed. Reversal pivot targets Small.',
  },
  {
    id: 'P183',
    name: '🔮 LUCAS SERIES 1-3-4 (S-B-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Lucas 1-3-4 harmonic step completed. Reversal pivot targets Big.',
  },
  {
    id: 'P184',
    name: '📐 GOLDEN RATIO 3:5 EQUILIBRIUM (B-B-B-S-S-S-S-S ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 97,
    description: '3:5 Golden ratio harmonic boundary reached. Mean rebound to Big.',
  },
  {
    id: 'P185',
    name: '📐 GOLDEN RATIO 3:5 EQUILIBRIUM (S-S-S-B-B-B-B-B ➔ S)',
    sequence: ['S', 'S', 'S', 'B', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 97,
    description: '3:5 Golden ratio harmonic boundary reached. Mean rebound to Small.',
  },
  {
    id: 'P186',
    name: '🔮 2-1-3 HARMONIC FLIP (B-B-S-B-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 96,
    description: '2-1-3 Harmonic cadence peaks on 3rd Big. Pivot to Small.',
  },
  {
    id: 'P187',
    name: '🔮 2-1-3 HARMONIC FLIP (S-S-B-S-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 96,
    description: '2-1-3 Harmonic cadence peaks on 3rd Small. Pivot to Big.',
  },
  {
    id: 'P188',
    name: '📐 PRIME 2-3-5 EXPANSION WAVE (B-B-S-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Prime number step distribution predicts pivot to Small.',
  },
  {
    id: 'P189',
    name: '📐 PRIME 2-3-5 EXPANSION WAVE (S-S-B-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Prime number step distribution predicts pivot to Big.',
  },
  {
    id: 'P190',
    name: '🔮 HARMONIC OSCILLATION OCTAVE (B-S-B-B-S-B-B ➔ S)',
    sequence: ['B', 'S', 'B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 95,
    description: 'Harmonic octave recurrence locks on Small.',
  },
  {
    id: 'P191',
    name: '🔮 HARMONIC OSCILLATION OCTAVE (S-B-S-S-B-S-S ➔ B)',
    sequence: ['S', 'B', 'S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 95,
    description: 'Harmonic octave recurrence locks on Big.',
  },
  {
    id: 'P192',
    name: '📐 GOLDEN MEAN 5:3 COMPRESSION (B5-S3 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 97,
    description: '5:3 Golden mean compression resets to Big.',
  },
  {
    id: 'P193',
    name: '📐 GOLDEN MEAN 5:3 COMPRESSION (S5-B3 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 97,
    description: '5:3 Golden mean compression resets to Small.',
  },
  {
    id: 'P194',
    name: '🔮 FIBONACCI STEP 4 EXTENSION (B-S-B-B-S-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'S', 'B', 'B', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 98,
    description: 'Deep Fibonacci 1-1-2-3-4 cycle completed. Full pivot to Small.',
  },
  {
    id: 'P195',
    name: '🔮 FIBONACCI STEP 4 EXTENSION (S-B-S-S-B-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'B', 'S', 'S', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 98,
    description: 'Deep Fibonacci 1-1-2-3-4 cycle completed. Full pivot to Big.',
  },
  {
    id: 'P196',
    name: '📐 2-1-1-2 GOLDEN SANDWICH (B-B-S-B-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 96,
    description: '2-1-1-2 Symmetric sandwich completed. Bounce targets Big.',
  },
  {
    id: 'P197',
    name: '📐 2-1-1-2 GOLDEN SANDWICH (S-S-B-S-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 96,
    description: '2-1-1-2 Symmetric sandwich completed. Bounce targets Small.',
  },
  {
    id: 'P198',
    name: '🔮 3-2-1-1 DECELERATING HARMONIC (B-B-B-S-S-B-S ➔ B)',
    sequence: ['B', 'B', 'B', 'S', 'S', 'B', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 95,
    description: 'Decelerating harmonic cadence rebound to Big.',
  },
  {
    id: 'P199',
    name: '🔮 3-2-1-1 DECELERATING HARMONIC (S-S-S-B-B-S-B ➔ S)',
    sequence: ['S', 'S', 'S', 'B', 'B', 'S', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 95,
    description: 'Decelerating harmonic cadence rebound to Small.',
  },
  {
    id: 'P200',
    name: '📐 GOLDEN DOUBLE RATIO (B-B-S-S-S-B-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 96,
    description: 'Golden double ratio 2-3-3 inflection targets Small.',
  },
  {
    id: 'P201',
    name: '📐 GOLDEN DOUBLE RATIO (S-S-B-B-B-S-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 96,
    description: 'Golden double ratio 2-3-3 inflection targets Big.',
  },
  {
    id: 'P202',
    name: '🔮 FIBONACCI STEP PEAK (B-B-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Twin into quad climax. Reversal to Small.',
  },
  {
    id: 'P203',
    name: '🔮 FIBONACCI STEP PEAK (S-S-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 97,
    description: 'Twin into quad climax. Reversal to Big.',
  },
  {
    id: 'P204',
    name: '📐 GOLDEN SPIRAL CORE (B-S-B-B-B-S-S ➔ B)',
    sequence: ['B', 'S', 'B', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'FIBONACCI',
    confidence: 96,
    description: 'Golden spiral core expansion targets Big.',
  },
  {
    id: 'P205',
    name: '📐 GOLDEN SPIRAL CORE (S-B-S-S-S-B-B ➔ S)',
    sequence: ['S', 'B', 'S', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'FIBONACCI',
    confidence: 96,
    description: 'Golden spiral core expansion targets Small.',
  },

  // =========================================================================
  // CATEGORY 7: MACRO STATISTICAL REGIMES & PARITY BOUNDARY SHIFTS (P206 - P235)
  // =========================================================================
  {
    id: 'P206',
    name: '🌐 10-RESULT BIG SATURATION (B7/10 ➔ S)',
    sequence: ['B', 'B', 'B', 'S', 'B', 'B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 98,
    description: 'Big oversaturated 8/10 in macro window. Systematic mean-reversion to Small.',
  },
  {
    id: 'P207',
    name: '🌐 10-RESULT SMALL SATURATION (S7/10 ➔ B)',
    sequence: ['S', 'S', 'S', 'B', 'S', 'S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 98,
    description: 'Small oversaturated 8/10 in macro window. Systematic mean-reversion to Big.',
  },
  {
    id: 'P208',
    name: '⚖️ 10-RESULT PERFECT 5:5 EQUILIBRIUM (B-S-B-S-B-S-B-S-S-B ➔ S)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'S', 'B', 'S', 'S', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: '5:5 Parity equilibrium rotation. Phase oscillation to Small.',
  },
  {
    id: 'P209',
    name: '⚖️ 10-RESULT PERFECT 5:5 EQUILIBRIUM (S-B-S-B-S-B-S-B-B-S ➔ B)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'B', 'S', 'B', 'B', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: '5:5 Parity equilibrium rotation. Phase oscillation to Big.',
  },
  {
    id: 'P210',
    name: '🟣 VIOLET NUMBER 0 POLARITY PIVOT (0-VIOLET ➔ B)',
    sequence: ['S', 'S', 'S', 'S', 'S'], // zero belongs to Small
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 97,
    description: 'Violet 0 marker signifies extreme lower boundary. Reversal upward to Big.',
  },
  {
    id: 'P211',
    name: '🟣 VIOLET NUMBER 5 POLARITY PIVOT (5-VIOLET ➔ S)',
    sequence: ['B', 'B', 'B', 'B', 'B'], // 5 belongs to Big
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 97,
    description: 'Violet 5 marker signifies threshold boundary. Reversal downward to Small.',
  },
  {
    id: 'P212',
    name: '📊 6:4 PARITY ROTATION (B-B-S-B-B-S-B-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B', 'B', 'S', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: '6:4 Parity pressure triggers rotational switch to Small.',
  },
  {
    id: 'P213',
    name: '📊 6:4 PARITY ROTATION (S-S-B-S-S-B-S-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S', 'S', 'B', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: '6:4 Parity pressure triggers rotational switch to Big.',
  },
  {
    id: 'P214',
    name: '🌐 HIGH DEFICIT PULLBACK (S-S-S-S-S-B-S ➔ B)',
    sequence: ['S', 'S', 'S', 'S', 'S', 'B', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: 'Macro deficit pullback recovery enforces second Big step.',
  },
  {
    id: 'P215',
    name: '🌐 HIGH DEFICIT PULLBACK (B-B-B-B-B-S-B ➔ S)',
    sequence: ['B', 'B', 'B', 'B', 'B', 'S', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: 'Macro deficit pullback recovery enforces second Small step.',
  },
  {
    id: 'P216',
    name: '📈 PARITY CLUSTER EXPANSION (B-S-B-B-S-B-B-B ➔ S)',
    sequence: ['B', 'S', 'B', 'B', 'S', 'B', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: 'Triple Big ending cluster expansion. Mean reversion to Small.',
  },
  {
    id: 'P217',
    name: '📈 PARITY CLUSTER EXPANSION (S-B-S-S-B-S-S-S ➔ B)',
    sequence: ['S', 'B', 'S', 'S', 'B', 'S', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 96,
    description: 'Triple Small ending cluster expansion. Mean reversion to Big.',
  },
  {
    id: 'P218',
    name: '🔄 3-STEP ALTERNATION CASCADE (B-B-S-B-B-S-B-B ➔ S)',
    sequence: ['B', 'B', 'S', 'B', 'B', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 97,
    description: '2-1-2-1-2 periodic parity cadence targets Small.',
  },
  {
    id: 'P219',
    name: '🔄 3-STEP ALTERNATION CASCADE (S-S-B-S-S-B-S-S ➔ B)',
    sequence: ['S', 'S', 'B', 'S', 'S', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 97,
    description: '2-1-2-1-2 periodic parity cadence targets Big.',
  },
  {
    id: 'P220',
    name: '🌐 12-ROUND MACRO CYCLE PIVOT (B-S-S-B-B-B-S-B-S-S-B-B ➔ S)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'B', 'S', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 98,
    description: '12-Round macro structural cycle transition locks on Small.',
  },
  {
    id: 'P221',
    name: '🌐 12-ROUND MACRO CYCLE PIVOT (S-B-B-S-S-S-B-S-B-B-S-S ➔ B)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'S', 'B', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 98,
    description: '12-Round macro structural cycle transition locks on Big.',
  },
  {
    id: 'P222',
    name: '⚡ MARKOV TRANSITION PROBABILITY MATRIX (B-S-B-B-S-S ➔ B)',
    sequence: ['B', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 97,
    description: 'Markov 2nd-order state matrix evaluates highest probability transition to Big.',
  },
  {
    id: 'P223',
    name: '⚡ MARKOV TRANSITION PROBABILITY MATRIX (S-B-S-S-B-B ➔ S)',
    sequence: ['S', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 97,
    description: 'Markov 2nd-order state matrix evaluates highest probability transition to Small.',
  },
  {
    id: 'P224',
    name: '🌐 14-ROUND DEEP CONVERGENCE (B-S-B-S-S-B-B-S-B-S-S-B-S-B ➔ B)',
    sequence: ['B', 'S', 'B', 'S', 'S', 'B', 'B', 'S', 'B', 'S', 'S', 'B', 'S', 'B'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '14-Round deep pattern convergence locks on Big.',
  },
  {
    id: 'P225',
    name: '🌐 14-ROUND DEEP CONVERGENCE (S-B-S-B-B-S-S-B-S-B-B-S-B-S ➔ S)',
    sequence: ['S', 'B', 'S', 'B', 'B', 'S', 'S', 'B', 'S', 'B', 'B', 'S', 'B', 'S'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '14-Round deep pattern convergence locks on Small.',
  },
  {
    id: 'P226',
    name: '👑 BOSS MASTER ULTIMATE LOCK (B-B-B-S-B-S-B-B-S-S-B-B ➔ S)',
    sequence: ['B', 'B', 'B', 'S', 'B', 'S', 'B', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: 'Boss Master algorithm completes full parity matrix. Invariant execution to Small.',
  },
  {
    id: 'P227',
    name: '👑 BOSS MASTER ULTIMATE LOCK (S-S-S-B-S-B-S-S-B-B-S-S ➔ B)',
    sequence: ['S', 'S', 'S', 'B', 'S', 'B', 'S', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: 'Boss Master algorithm completes full parity matrix. Invariant execution to Big.',
  },
  {
    id: 'P228',
    name: '⚡ 15-ROUND SYNCHRONOUS CADENCE (B-S-S-B-B-S-S-B-B-S-S-B-B-S-S ➔ B)',
    sequence: ['B', 'S', 'S', 'B', 'B', 'S', 'S', 'B', 'B', 'S', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '15-Round multi-twin harmonic recursion locks on Big.',
  },
  {
    id: 'P229',
    name: '⚡ 15-ROUND SYNCHRONOUS CADENCE (S-B-B-S-S-B-B-S-S-B-B-S-S-B-B ➔ S)',
    sequence: ['S', 'B', 'B', 'S', 'S', 'B', 'B', 'S', 'S', 'B', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '15-Round multi-twin harmonic recursion locks on Small.',
  },
  {
    id: 'P230',
    name: '💎 2:2:2:2 OCTO TWIN COMPLETE (B-B-S-S-B-B-S-S-B-B-S-S ➔ B)',
    sequence: ['B', 'B', 'S', 'S', 'B', 'B', 'S', 'S', 'B', 'B', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '12-Round octo-twin sequence completes. Hard rotation to Big.',
  },
  {
    id: 'P231',
    name: '💎 2:2:2:2 OCTO TWIN COMPLETE (S-S-B-B-S-S-B-B-S-S-B-B ➔ S)',
    sequence: ['S', 'S', 'B', 'B', 'S', 'S', 'B', 'B', 'S', 'S', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '12-Round octo-twin sequence completes. Hard rotation to Small.',
  },
  {
    id: 'P232',
    name: '🌊 16-ROUND TSUNAMI CADENCE (B4-S4-B4-S4 ➔ B)',
    sequence: ['B', 'B', 'B', 'B', 'S', 'S', 'S', 'S', 'B', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '16-Round Quad-Tsunami macro rhythm completed. Invariant rebound to Big.',
  },
  {
    id: 'P233',
    name: '🌊 16-ROUND TSUNAMI CADENCE (S4-B4-S4-B4 ➔ S)',
    sequence: ['S', 'S', 'S', 'S', 'B', 'B', 'B', 'B', 'S', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '16-Round Quad-Tsunami macro rhythm completed. Invariant rebound to Small.',
  },
  {
    id: 'P234',
    name: '🏛️ 18-ROUND SUPREME PINNACLE (B-S-B-S-B-B-S-S-B-B-B-S-S-S-B-B-B-B ➔ S)',
    sequence: ['B', 'S', 'B', 'S', 'B', 'B', 'S', 'S', 'B', 'B', 'B', 'S', 'S', 'S', 'B', 'B', 'B', 'B'],
    next: 'S',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '18-Round master harmonic staircase completed. Terminal pivot to Small.',
  },
  {
    id: 'P235',
    name: '🏛️ 18-ROUND SUPREME PINNACLE (S-B-S-B-S-S-B-B-S-S-S-B-B-B-S-S-S-S ➔ B)',
    sequence: ['S', 'B', 'S', 'B', 'S', 'S', 'B', 'B', 'S', 'S', 'S', 'B', 'B', 'B', 'S', 'S', 'S', 'S'],
    next: 'B',
    category: 'MACRO_PARITY',
    confidence: 99,
    description: '18-Round master harmonic staircase completed. Terminal pivot to Big.',
  },
];
